import { Rubik } from "next/font/google";
import "./globals.css";

const inter = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="he" dir="rtl">
      <body className={inter.className}>
        <div className="wrapper">
          <h1 className="header">איפה האוטו שלי?!</h1>
        </div>
        {children}
      </body>
    </html>
  );
}
